# Generated by Django 3.0.2 on 2020-01-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('World_Diseases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='deaths_sufferers_per_country_per_year',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rate_of_spread',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
