# Generated by Django 3.0.2 on 2020-01-08 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('World_Diseases', '0003_research_labs_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research_labs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
