# Generated by Django 3.0.2 on 2020-01-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('World_Diseases', '0004_auto_20200108_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funding',
            name='date_of_report',
        ),
    ]
