# Generated by Django 3.0.2 on 2020-01-13 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('World_Diseases', '0006_auto_20200109_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research_labs',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
