# Generated by Django 3.0.2 on 2020-01-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('World_Diseases', '0007_auto_20200113_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
        migrations.AddField(
            model_name='research_labs',
            name='lab_image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
