# Generated by Django 3.0.2 on 2020-01-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('World_Diseases', '0008_auto_20200113_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/profile_image/blank-profile.png', upload_to='profile_image'),
        ),
    ]
