# Generated by Django 3.0.2 on 2020-01-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('World_Diseases', '0010_auto_20200114_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research_labs',
            name='lab_image',
            field=models.ImageField(blank=True, default='profile_image/default_lab_image.jpg', upload_to='profile_image'),
        ),
    ]
