# Generated by Django 3.0.2 on 2020-01-15 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('World_Diseases', '0011_auto_20200114_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research_labs',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='World_Diseases.Diseases'),
        ),
    ]
