# Generated by Django 3.0.2 on 2020-02-03 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('World_Diseases', '0012_auto_20200115_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor_favorite_labs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.ManyToManyField(blank=True, to='World_Diseases.Research_labs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
