# Generated by Django 3.0.2 on 2020-01-19 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('World_Diseases', '0012_auto_20200115_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor_wish_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='World_Diseases.Donor')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='World_Diseases.Research_labs')),
            ],
        ),
    ]
