# Generated by Django 3.0.2 on 2020-02-03 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('World_Diseases', '0014_auto_20200203_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_favorite_labs',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='World_Diseases.Research_labs'),
        ),
    ]
